Ajout de 70 blagues
Blagues-API/blagues-api pull request #50
Opened 2021-07-07 22:25 UTC by saphirrc

70 blagues ajoutées ainsi que correction d'une faute de ponctuation

2021-07-08 09:38 UTC, ErwanGit requested changes
Corrections

2021-07-08 09:38 UTC, ErwanGit commented on blagues.json
> +    "joke": "Un gars et une fille en sont à leur première date... Le gars amène la fille en voiture au Mont-Royal, les deux commencent à s'embrasser. Lorsqu'ils sont sur le point de faire l'amour, la
La blague est peut-être un peu longue

2021-07-08 09:38 UTC, ErwanGit commented on blagues.json
> +    "answer": "Belle ceinture"
Je ne l'ai pas compris

2021-07-12 11:06 UTC, DraftProducts commented on blagues.json
> +    "joke": "Un gars et une fille en sont à leur première date... Le gars amène la fille en voiture au Mont-Royal, les deux commencent à s'embrasser. Lorsqu'ils sont sur le point de faire l'amour, la
Oui 👍

2021-07-12 11:06 UTC, DraftProducts commented on blagues.json
> +    "answer": "Belle ceinture"
Le 8 est un 0 avec un genre de nœud au milieu.

2021-07-12 11:16 UTC, DraftProducts requested changes
Je penses que tu n'as pas regardé si elles existaient déjà @saphirrc.
Pense a vérifier les blagues ne sont pas déjà dans l'API avant de faire une PR.
ça oblige a revoir tous les ID's.

2021-07-12 11:16 UTC, DraftProducts commented on blagues.json
> +    "answer": "Parce que sinon il ferait 2 pages."
Soit à reformuler soit à supprimer.

2021-07-12 11:16 UTC, DraftProducts commented on blagues.json
> +    "answer": "Un enfant dans deux poubelles."
Duplicata de la blague #124

2021-07-12 11:16 UTC, DraftProducts commented on blagues.json
> +    "answer": "Un arabe ! Il est partie à la piscine en marchant, il a nagé et il repartit en vélo."
Duplicata de la blague #603

2021-07-12 11:16 UTC, DraftProducts commented on blagues.json
> +    "answer": "Si c'est noir, c'est raté."
Duplicata de la blague #621

2021-07-12 11:16 UTC, DraftProducts commented on blagues.json
> +    "answer": "Car ils ont perdu leurs 2 tours."
Duplicata de la blague #412

2021-07-12 12:24 UTC, ErwanGit requested changes
Multiples corrections

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1039,
    "type": "global",
    "joke": "Dans quel endroit on peut trouver le plus de pigeons ?",
    "answer": "Dans un Apple Store."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1070,
    "type": "global",
    "joke": "Une momies fâchée quitte ses amies :",
    "answer": "Puisque c'est comme ça, je ne fait plus partie de la bande."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1061,
    "type": "beauf",
    "joke": "Quelle est la différence entre des haricots et un pet ?",
    "answer": "Environ 1 heure."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1034,
    "type": "dev",
    "joke": "Tu ne serais pas un câble Ethernet ?",
    "answer": "Car je sens qu'il y a une connexion entre nous deux."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1025,
    "type": "dark",
    "joke": "Pourquoi une imprimante arabe ne peux pas fonctionner ?",
    "answer": "Car elle n'a pas de papiers."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1024,
    "type": "dark",
    "joke": "Les blagues noires c'est comme les enfants qui ont le cancer,",
    "answer": "ça ne vieillit jamais..."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
j
```suggestion
  {
    "id": 1019,
    "type": "global",
    "joke": "Pourquoi les marins ne peuvent t'ils pas écrire ?",
    "answer": "Parce qu'ils ont jeté l'ancre."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1014,
    "type": "dark",
    "joke": "Savez-vous pourquoi le petit Grégory n'était jamais en retard ?",
    "answer": "Parce qu'il était dans l'étang !"
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1073,
    "type": "dark",
    "joke": "Quels sont les publics visés par Kinders ?",
    "answer": "Les enfants et les pédophiles."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1066,
    "type": "dark",
    "joke": "Qu'est-ce qu'un un selfie pour un orphelin ?",
    "answer": "Une photo de famille."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1062,
    "type": "beauf",
    "joke": "Pourquoi les tornades ont-elles des noms féminins ?",
    "answer": "Pour deux raisons, la première parce qu’elles arrivent chaudes et humides et la deuxième parce qu’elles repartent avec tes affaires."
  },
```
Après, la réponse à la blague est peut-être un peu longue

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  {
```suggestion
  {
    "id": 1044,
    "type": "dark",
    "joke": "Qu'est-ce qu'un groupe de somaliens sur un fond blanc ?",
    "answer": "Un code-barre."
  },
  {
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1043,
    "type": "global",
    "joke": "L'œil droit dit à l'œil gauche :",
    "answer": "\"Je sens quelque chose entre nous.\""
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1040,
    "type": "dark",
    "joke": "Quel est le meilleur antivol ?",
    "answer": "Un jambon."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1035,
    "type": "blondes",
    "joke": "Une blonde dit à son amie qu'elle a raté son permis car elle a vu un panneau 50 avant un rond point, \"J'ai fait 50 fois le tour du rond point\", dit-elle",
    "answer": "Son amie lui répond : \"Et tu t'es trompée de combien de tours ?\""
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1032,
    "type": "global",
    "joke": "Qu'est-ce qui est bleu et qui sent comme de la peinture rouge ?",
    "answer": "De la peinture bleue."
  },
```

2021-07-12 12:24 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1016,
    "type": "global",
    "joke": "Qu'est-ce qui fait rire un cuisinier ?",
    "answer": "Une farce."
  },
```

2021-07-12 18:22 UTC, saphirrc commented on blagues.json
> +  },
Il n'y a pas de verbe donc pas de point.

2021-07-12 19:25 UTC, ErwanGit requested changes

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1073,
    "type": "dark",
    "joke": "Quelle est la différence entre un couple Gay et un couple Hétéro ?",
    "answer": "Le couple Hétéro se démontent et le couple Gay s’emboîtent."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1071,
    "type": "dark",
    "joke": "Quels sont les publics visés par Kinders ?",
    "answer": "Les enfants et les pédophiles"
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1068,
    "type": "global",
    "joke": "Une momies fâchée quitte ses amies :",
    "answer": "Puisque c'est comme ça, je ne fait plus partie de la bande."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1064,
    "type": "dark",
    "joke": "Qu'est-ce qu'un un selfie pour un orphelin ?",
    "answer": "Une photo de famille"
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1059,
    "type": "beauf",
    "joke": "Pourquoi les tornades ont-elles des noms féminins ?",
    "answer": "Pour deux raisons, la première parce qu’elles arrivent chaudes et humides et la deuxième parce qu’elles repartent avec tes affaires."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  },
  {
    "id": 1054,
    "type": "limit",
    "joke": "Comment appelle t-on une actrice porno qui tombe enceinte ?",
    "answer": "Un accident de travail."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1052,
    "type": "limit",
    "joke": "Quelle est la différence entre un vieux et un renard ?",
    "answer": "Le renard a la queue touffue et le vieux a la queue foutue."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1049,
    "type": "dark",
    "joke": "Comment faire rentrer 20 juifs dans la voiture ?",
    "answer": "Deux à l'avant, trois à l'arrière, deux dans le coffre et tous les autres dans le cendrier !"
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1023,
    "type": "global",
    "joke": "Pourquoi certaines personnes jettent-elles leurs ordinateurs à la mer ?",
    "answer": "Pour surfer sur le net."
  },
```
J'ai un petit doute mais pour moi, c'est ça

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1022,
    "type": "global",
    "joke": "Comment appelle-t-on un avion qui rebondit ?",
    "answer": "Un boing !"
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1019,
    "type": "dark",
    "joke": "Les blagues noires c'est comme les enfants qui ont le cancer,",
    "answer": "ça ne vieillit jamais..."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1014,
    "type": "global",
    "joke": "Pourquoi les marins ne peuvent t'il pas écrire ?",
    "answer": "Parce qu'ils ont jeté l'ancre."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1009,
    "type": "dark",
    "joke": "Savez-vous pourquoi le petit Grégory n'était jamais en retard ?",
    "answer": "Parce qu'il était dans l'étang !"
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1034,
    "type": "global",
    "joke": "Dans quel endroit peut-on peut trouver le plus de pigeons ?",
    "answer": "Dans un Apple Store."
  },
```

2021-07-12 19:25 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1037,
    "type": "global",
    "joke": "Un père dit à son fils : \"Ton professeur a-t'il remarqué que je t'avais aidé pour ton devoir ?\"",
    "answer": "\"Je ne sais pas, il a juste dit que c'était impossible que je fasse autant de fautes\"."
  },
```

2021-07-12 19:27 UTC, ErwanGit commented on blagues.json
> +  },
C'est bon pour moi 👍

2021-07-12 19:35 UTC, ErwanGit requested changes
Oublie de la seconde review

2021-07-12 19:35 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1020,
    "type": "dark",
    "joke": "Pourquoi une imprimante arabe ne peux pas fonctionné ?",
    "answer": "Car elle n'a pas de papiers."
  },
```

2021-07-13 12:32 UTC, ErwanGit commented
@saphirrc C'est normal que toutes les corrections n'ont pas encore été effectué malgré ton commit ?

2021-07-13 13:29 UTC, ErwanGit submitted a review, later dismissed

2021-07-13 13:29 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1067,
    "type": "global",
    "joke": "Une momie fâchée quitte ses amies :",
    "answer": "Puisque c'est comme ça, je ne fait plus partie de la bande"
  },
```

2021-07-14 08:15 UTC, DraftProducts approved these changes

2021-07-14 08:59 UTC, ErwanGit requested changes

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1014,
    "type": "global",
    "joke": "Pourquoi les marins ne peuvent t'ils pas écrire ?",
    "answer": "Parce qu'ils ont jeté l'ancre."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1022,
    "type": "global",
    "joke": "Comment appelle-t-on un avion qui rebondit ?",
    "answer": "Un boing !"
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1023,
    "type": "global",
    "joke": "Pourquoi certaines personnes jettent-elles leurs ordinateurs à la mer ?",
    "answer": "Pour surfer sur le net."
  },
```
J'ai un doute sur cette correction mais pour moi, c'est ça

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1040,
    "type": "dark",
    "joke": "Pourquoi Harry Potter est-il une fiction ?",
    "answer": "Le héro a un ami roux."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1045,
    "type": "limit",
    "joke": "Que dit un éléphant à un nudiste ?",
    "answer": "\"Alors c'est avec ça que tu bois ?\""
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1048,
    "type": "dark",
    "joke": "Comment faire rentrer 20 juifs dans la voiture ?",
    "answer": "Deux à l'avant, trois à l'arrière, deux dans le coffre et tous les autres dans le cendrier !"
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1050,
    "type": "global",
    "joke": "Pourquoi les vaches ferment-elles les yeux ?",
    "answer": "Pour faire du lait concentré."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1051,
    "type": "limit",
    "joke": "Quelle est la différence entre un vieux et un renard ?",
    "answer": "Le renard a la queue touffue et le vieux a la queue foutue."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
La blague est trop longue

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1070,
    "type": "dark",
    "joke": "Quelle est la différence entre un couple Gay et un couple Hétéro ?",
    "answer": "Le couple Hétéro se démontent et le couple Gay s’emboîtent."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +  },
```suggestion
  {
    "id": 1032,
    "type": "dark",
    "joke": "Je vais appeler mon enfant Plainte.",
    "answer": "Au moins je pourrais porter Plainte."
  },
```

2021-07-14 08:59 UTC, ErwanGit commented on blagues.json
> +    "joke": "Deux ouvriers vont travailler sur la Tour Eiffel. Soudain, ils s'aperçoivent qu'ils ont oublié leur mètre. A quelle hauteur sont-ils ?",
```suggestion
    "joke": "Deux ouvriers vont travailler sur la Tour Eiffel. Soudain, ils s'aperçoivent qu'ils ont oublié leur mètre. À quelle hauteur sont-ils ?",
```

2021-07-14 09:02 UTC, DraftProducts commented on blagues.json
> +  },
👍 Je serais pour sa suppression

2021-07-14 10:33 UTC, saphirrc commented on blagues.json
> +  },
Je vois pas vraiment pourquoi ça serait au pluriel.

2021-07-14 10:34 UTC, DraftProducts commented on blagues.json
> +  },
Nop, je penses que c'est bien `leur ordinateur`

2021-07-14 10:36 UTC, ErwanGit commented on blagues.json
> +  },
> Je vois pas vraiment pourquoi ça serait au pluriel.

@saphirrc Il y a plusieurs ordinateurs

2021-07-14 15:35 UTC, ErwanGit approved these changes

2021-07-15 11:43 UTC, merged